# Generated by Django 3.2.9 on 2021-11-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('County', models.TextField(max_length=300)),
                ('Total_x', models.CharField(max_length=300)),
                ('Male_x', models.CharField(max_length=300)),
                ('Female_x', models.CharField(max_length=300)),
                ('Total_y', models.CharField(max_length=300)),
                ('Male_y', models.CharField(max_length=300)),
                ('Female_Y', models.CharField(max_length=300)),
                ('Intersex', models.CharField(max_length=300)),
                ('Population', models.CharField(max_length=300)),
                ('Land', models.CharField(max_length=300)),
                ('ppdens', models.CharField(max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
